export type Category = 'All' | 'MT' | 'PT' | 'CL' | 'GP';

export interface Product {
  name: string;
  slug: string;
  category: Category;
  description: string;
  features: string[];
  image: string;
  specifications?: string[];
  advantages?: string[];
}

export const categories: { id: Category; label: string }[] = [
  { id: 'All', label: 'All Products' },
  { id: 'MT', label: 'MT \u2013 Microbiological Testing' },
  { id: 'PT', label: 'PT \u2013 Physico-chemical Testing' },
  { id: 'CL', label: 'ML \u2013 Mobile Laboratory' },
  { id: 'GP', label: 'GP \u2013 General Products' },
];

export const products: Product[] = [
  {
    name: 'LETZTEST Tube',
    slug: 'letztest-tube',
    category: 'MT',
    description: 'An easy-to-use presence/absence test for detecting fecal bacteria in water samples. This ready-to-use test is ideal for routine monitoring of drinking water systems in remote locations.\n\nThe presence of fecal bacteria in water is a clear indication of contamination from human or animal excrement, which carries a high risk of pathogenic microorganisms causing severe waterborne diseases (e.g. Cholera). Monitoring fecal bacteria is crucial to ensure safe drinking water and safeguard public health. According to the World Health Organization (WHO) drinking water guidelines, safe water must not contain any fecal indicator bacteria.\n\n(Reference: WHO Guidelines for Drinking-water Quality, Fourth Edition, 2011, page 36)',
    features: ['Detects coliforms & E.coli', 'Results in 24 hours', 'No lab equipment needed', 'Includes 50 tests'],
    image: '/letztest%20tube.jpeg',
    specifications: ['Detects: Presence/absence of fecal bacteria in water samples', 'Made In: Germany', 'Ready to Ship: Upon request, usually 10 days', 'Form: Dry test strip in PP tube', 'Dimensions: 90x25 mm + lock, 25 ml', 'Weight: 9 g', 'Shelf-life: 2 years', 'Storage temperature: 1-30°C (no cooling required)'],
    advantages: ['Ready to use', 'Cost and time effective', 'Local recycling into new test tubes at LETZTEST distributors site possible', 'Easy to use', 'Easy to evaluate', 'Non-sensitive to errors', 'Incubation at room temperature possible', 'Easy to store (no cooling, long shelf life)', 'Easy to transport'],
  },
  {
    name: 'LETZTEST Household Water Test Kit',
    slug: 'letztest-household-water-test-kit',
    category: 'MT',
    description: 'The Household Water Test Kit is an educational presence/absence test kit, protected by patent office, which detects bacteria of fecal origin in drinking water.\n\nIt is used in particular in the context of community and household awareness raising operations: possible contamination between an improved water source, serving good quality water, and the point of consumption at household level can be discussed.\n\nThe presence of fecal bacteria in water is a clear indication of contamination from human or animal excrement, which carries a high risk of pathogenic microorganisms causing severe waterborne diseases (e.g. Cholera).\n\nMonitoring fecal bacteria is crucial to ensure safe drinking water and safeguard public health. According to the World Health Organization (WHO) drinking water guidelines, safe water must not contain any fecal indicator bacteria.',
    features: ['Detects fecal bacteria in water', 'Educational awareness tool', 'No laboratory required', 'Clear illustrated instructions', 'Multi-barrier approach (WHO)', 'Ideal for community outreach'],
    image: '/household%20water%20test%20Kit.jpg',
    specifications: ['Detects: Presence/absence of fecal bacteria', 'Made in: Germany', 'Ready to Ship: Upon request, usually 10 days', 'Form: Recycled paper box', 'Dimensions: 173 x 109 x 100 mm', 'Weight: 280g', 'Shelf-life: 2 years', 'Storage temperature: 1-30°C (no cooling required)'],
    advantages: ['Ready to use', 'Cost and time effective', 'Local recycling into new test tubes at LETZTEST distributors site possible', 'Easy to use', 'Easy to evaluate', 'Non-sensitive to errors', 'Incubation at room temperature possible', 'Easy to store (no cooling, long shelf life)', 'Easy to transport'],
  },
  {
    name: 'LETZTEST Portable Membrane Filtration Kit',
    slug: 'letztest-portable-membrane-filtration-kit',
    category: 'MT',
    description: 'The LETZTEST Portable Membrane Filtration Kit quantifies E.coli and other fecal indicator bacteria per 100 mL in water samples following DIN EN ISO 9308-1, even in the most remote locations in the field or for mobile laboratories.\n\nThe presence of fecal bacteria in water is a clear indication of contamination from human or animal excrement, which carries a high risk of pathogenic microorganisms causing severe waterborne diseases (e.g. Cholera). Monitoring fecal bacteria is crucial to ensure safe drinking water and safeguard public health. According to the World Health Organization (WHO) drinking water guidelines, safe water must not contain any fecal indicator bacteria.',
    features: ['Portable design', 'Membrane filtration method', 'Field-ready', 'Comprehensive kit'],
    image: '/portable%20membrane.png',
    specifications: ['Art. No.: 115433 (English), 118193 (French), 1155 (Arabic), 118197 (Spanish)', 'Training: Recommended', 'Quantifies: Escherichia coli in water', 'Made In: Germany', 'Ready to Ship: Upon request, usually 10 days', 'Form: Hard-shell case', 'Dimensions: 450 x 360 x 175 mm', 'Weight: 8.6 kg', 'Shelf-life: n/a', 'Storage temperature: n/a'],
    advantages: ['Ultra-robust: All hardware parts made of thick pharmaceutical-grade stainless steel, produced in Germany', 'Independent of current or battery', 'Low operating costs', 'Quick results', 'Few consumables without requirement of cooling', 'Simplified, methanol-free sterilisation', 'Easy to transport (by motorbike)', 'Simple processes', 'Insensitive to errors', 'Automatic counting of colonies using smartphone app', 'Testing of larger number of samples compared to comparable kits', 'Robust case with low carbon footprint, made in Italy', 'Rewritable illustrated handbook with easily understandable instructions (English, French, Arabic, Spanish)'],
  },
  {
    name: 'LETZTEST Electricity-Free Incubators',
    slug: 'letztest-electricity-free-incubators',
    category: 'MT',
    description: 'The game-changing incubators from LETZTEST – the world\'s first and only patent office protected solution to incubate water samples without electricity! Say goodbye to troublesome electrical or battery-powered incubators.\n\nThese lightweight and compact incubators are completely independent of electricity and batteries, providing a reliable way to test water quality in regions with unstable power supply. The LETZTEST Electricity-Free-Incubators are revolutionary products that make water quality testing in off-grid locations more practical and easier than ever before.\n\nTogether with our membrane filtration kits, these incubators form a portable laboratory for microbiological testing.',
    features: ['No electricity required', 'Maintains 37°C', 'Portable and rugged', 'Multiple sizes available'],
    image: '/electricity%20free.png',
    specifications: ['Art. No.: 115178 (size M), 1231 (size L)', 'Training: Recommended', '',
      '— Size M —', 'Purpose: Incubate water samples at 37°C without electricity', 'Made In: Germany', 'Ready to Ship: Upon request, usually 10 days', 'Form: Insulated bag made of fibreglass and aluminium', 'Dimensions: 400 x 300 x 130 mm', 'Weight: 4.5 kg', 'Shelf-life: n/a', 'Storage temperature: n/a', '',
      '— Size L —', 'Purpose: Incubate water samples at 37°C without electricity', 'Made In: Germany', 'Ready to Ship: Upon request, usually 10 days', 'Form: Insulated bag made of fibreglass and aluminium', 'Dimensions: 400 x 300 x 300 mm', 'Weight: 7.3 kg', 'Shelf-life: n/a', 'Storage temperature: n/a'],
    advantages: ['Independent of electricity', 'Lightweight and compact', 'Activate in the sun, with hot water, or with a USB heating mat', 'Maintains 37°C ± 0.5°C for at least 24 hours', 'Insensitive to errors and damage', 'Can also cool samples down to 37°C if outside temperature is higher'],
  },
  {
    name: 'LETZTEST Benchtop Membrane Filtration Kit',
    slug: 'letztest-benchtop-membrane-filtration-kit',
    category: 'MT',
    description: 'A complete and professional microbiological water laboratory, capable of processing very large amounts of samples per day to quantify E. coli and other fecal indicator bacteria per 100 ml in water samples following DIN EN ISO 9308-1.\n\nThe kit is perfect for central water labs to set up punctual time- and cost-efficient project laboratories in off-grid locations.\n\nFor optimal results, use it with the large model of the LETZTEST Electricity-Free Incubator.',
    features: ['Benchtop design', 'High precision filtration', 'Lab-grade components', 'Reusable setup'],
    image: '/benchtop%20membrane%20filtration.jpg',
    specifications: ['Art. No.: 1094', 'Training: Recommended', 'Quantifies: Escherichia coli and other coliform bacteria in water according to ISO 9308-1:2014 standard. Advantage: The same kit can be used to quantify other relevant bacteria in water such as enterococcus, pseudomonas aeruginosa, heterotrophic bacteria, total count bacteria and many more.', 'Made in: Europe', 'Ready to Ship: Upon request, usually 10 days', 'Form: Hard-shell case', 'Dimensions: 690 x 530 x 285 mm', 'Weight: 24 kg', 'Shelf-life: n/a', 'Storage temperature: Consumables Compact DRY Plates and ChroMedium Coliform Agar - 500g can be stored at room temperature'],
    advantages: ['Independent of current or battery in case of lack of electricity', 'Very low running costs of ~0.50€/sample possible by replacing two consumables with reusable solutions', 'Easy to transport (by motorbike) e.g. to a project laboratory', 'Easy to use', 'Automatic counting of colonies (=result) using a smartphone app', 'Insensitive to errors', 'Few consumables required', 'Easy storage of consumables (no cooling)', 'Simplified, methanol-free sterilisation', 'Testing of a larger number of samples compared to similar kits', 'All parts inside kit made in EU', 'Case with low carbon footprint in high quality and design made in Italy'],
  },
  {
    name: 'LETZTEST Water Sampler',
    slug: 'letztest-water-sampler',
    category: 'MT',
    description: 'This sampler is perfect for collecting water samples for microbiological analysis from hard-to-reach areas where direct sampling into a bottle or bag is not possible, such as storage tanks.',
    features: ['Sterile design', 'Easy to use', 'Prevents cross-contamination', 'Ideal for field sampling'],
    image: '/water%20sampler.png',
    specifications: ['Art. No.: 117952', 'Training: Recommended', 'Purpose: Take water samples from hard to reach sources', 'Sampling Volume: 350 ml', 'Material: 1.4404 stainless steel (pharmaceutical quality)', 'Made in: Germany', 'Ready to Ship: Upon request, usually < 10 days', 'Dimensions: 590 x 150 x 150 mm', 'Weight: 0.6 kg', 'Storage temperature: n/a'],
    advantages: ['Hand-welded with thick pharmaceutical-grade stainless steel', 'Ultra-robust and easy to disinfect', 'Practical when it is difficult to get to the water source'],
  },
  {
    name: 'LETZTEST Turbidity Tube',
    slug: 'letztest-turbidity-tube',
    category: 'PT',
    description: 'Simple, Safe and Independent. A very practical and very easy to use tool for visual measurement of water turbidity which is very often convincing in practice.\n\nAn essential test prior to water treatment by chlorination (Note: Chlorine is an effective disinfectant where water turbidity is below 5 NTU) and in ongoing water quality monitoring.',
    features: ['Measures turbidity in NTU', 'Easy-to-read scale', 'No batteries required', 'Durable construction'],
    image: '/turbidity%20tube.png',
    specifications: ['Art. No.: 117402', 'Training: No training required', 'Measuring range: 5 - 500 JTU', 'Made in: United Kingdom', 'Ready to Ship: Upon request, usually < 10 days', 'Form: Hard-shell case', 'Dimensions: 330 x 60 x 25 mm', 'Weight: 0.2 kg', 'Shelf-life: n/a', 'Storage temperature: n/a'],
    advantages: ['Very practical and user-friendly tool for visually measuring water turbidity', 'Proven reliability in remote locations', 'Consistently reliable in practical applications'],
  },
  {
    name: 'LETZTEST pH | Chlorine Tester',
    slug: 'letztest-ph-chlorine-tester',
    category: 'PT',
    description: 'The LETZTEST pH | Chlorine Tester is an easy to use tool for measuring free/residual chlorine, total chlorine and pH (acidity) of water samples which is very often convincing in practice.\n\nWhy measuring chlorine and pH? In many cases testers want to know if a water was disinfected or if the residual chlorine (=free chlorine) level is still sufficient to protect the drinking water from recontamination. The ideal level of free-residual chlorine is said to be 0.2-0.5 mg/L. Disinfection with chlorine is more effective at a pH value below 7.5.',
    features: ['Tests pH and chlorine', 'Fast results', 'Portable design', 'Easy calibration'],
    image: '/chlroine%20tester.png',
    specifications: ['Art. No.: 118311', 'Training: No training required', 'Detects: pH & free/residual/total chlorine', 'Content: Illustrated testing instruction; DPD1 reagent tablets (20 pcs) for free/residual chlorine; Phenol Red reagent tablets (20 pcs) for pH', 'Made in: United Kingdom', 'Ready to Ship: Upon request, usually < 10 days', 'Dimensions: 110 x 110 x 40 mm', 'Weight: 0.1 kg', 'Shelf-life: Tablets: 8 years', 'Storage temperature: No cooling required'],
    advantages: ['Practical visual color comparator test', 'Measures free and total chlorine as well as pH', 'Easy and user-friendly', 'Pocket-sized and portable', 'Long-lasting and cost-efficient reagents', 'Perfect solution for remote locations', 'Simple, safe and independent'],
  },
  {
    name: 'LETZTEST Visual Color Comparator Kit',
    slug: 'letztest-visual-color-comparator-kit',
    category: 'PT',
    description: 'The LETZTEST Visual Color Comparator Kit is an easy to use and comprehensive tool for measuring Alkalinity | Aluminum | Ammonia | Chloride | Chlorine free and total | Copper | Colour | Fluoride | Iron | Manganese | Nitrate | Nitrite | pH | Phosphate | Total Hardness and many more parameters.\n\nPriority parameters defined by the World Health Organisation to monitor easily with this kit:\n\nResidual Chlorine: Ensures water is disinfected and safe from disease causing bacteria of fecal origin. Ideal level is 0.2-0.5 mg/L. Chlorination of water systems is more efficient at pH < 7.5 and turbidity < 5 NTU.\n\nFluoride: Watch for teeth mottling at 1.5-4 mg/L, or skeletal fluorosis at > 4 mg/L. WHO limit: 1.5 mg/L.\n\nNitrate: High levels harm infants and pregnant women, causing blue baby syndrome and birth defects. WHO limit: 50 mg/L.\n\nManganese: Affects water taste, odor, and appearance. Can lead to water rejection by consumers. WHO limit: 0.4 mg/L.',
    features: ['Color comparison method', 'Tests multiple parameters', 'Includes reagents', '100+ tests per kit'],
    image: '/visual%20color%20comparator.png',
    specifications: ['Art. No.: 1164', 'Training: No training required', 'Parameters: Alkalinity | Aluminum | Ammonia | Chloride | Chlorine free and total | Copper | Colour | Fluoride | Iron | Manganese | Nitrate | Nitrite | pH | Phosphate | Total Hardness and more upon request', 'Made In: Germany', 'Ready to Ship: Upon request, usually 10 days', 'Form: Hard-shell case', 'Dimensions: 47 x 38 x 14 cm', 'Weight: 2.3 kg', 'Shelf-life: Up to 10 years without cooling', 'Storage temperature: Room temperature'],
    advantages: ['No maintenance or calibration', 'Independent of electricity or batteries', 'Long-lasting reagents are cost-efficient, non-toxic and do not require cooling', 'Rapid dissolving tablet reagents', 'Ongoing colour scale on a parameter stick', 'Convenient boxes for transport and storage', 'Easy push through blister'],
  },
  {
    name: 'LETZTEST Multimeter Kit',
    slug: 'letztest-multimeter-kit',
    category: 'PT',
    description: 'The LETZTEST Multimeter Kit measures various parameters in a very easy way such as pH, conductivity, salinity, Total Dissolved Solids, Oxygen Reduction Potential and Temperature. It works quickly and is suited for the use in remote locations.',
    features: ['Multiple parameters', 'Digital readout', 'Portable kit', 'Field-ready'],
    image: '/multimeter%20kit.png',
    specifications: ['Art. No.: 1165', 'Training: Recommended', 'Quantifies: pH | EC | Sal. | TDS | Temp. | ORP', 'Made In: Germany', 'Ready to Ship: Within 10 days', 'Form: Hard-shell case', 'Dimensions: 280 x 240 x 75 mm', 'Weight: 0.8 kg', 'Shelf-life: -', 'Storage temperature: 0 - 50°C'],
    advantages: ['Measures multiple parameters without additional reagents', 'Results displayed within seconds', 'Easy to use - simply dip in water sample', 'Portable and convenient for field use'],
  },
  {
    name: 'LETZTEST Photometer Kit',
    slug: 'letztest-photometer-kit',
    category: 'PT',
    description: 'The LETZTEST Photometer Kit enables the analysis of more than 140 physico-chemical water parameters with a single compact, high-precision device. Developed in Germany and equipped with 18 LEDs, it delivers reliable and accurate results.\n\nThe intuitive, multilingual touchscreen with QR code scanning ensures easy operation and sample tracking. Integrated cloud-based data management allows offline data recording with automatic synchronization, as well as analysis, visualization, and reporting.\n\nWith optional add-ons, the system can be transformed into a versatile multi-parameter meter. The Photometer ProbeBox Kit enables pH, EC, TDS, and ORP probe measurements, while additional equipment supports testing for COD, Legionella and more.\n\nThe LETZTEST Photometer Kit uses the exact same reagents as the LETZTEST Visual Colour Comparator Kit.',
    features: ['Digital photometer', 'High accuracy', 'Multiple test parameters', 'Data logging'],
    image: '/photometer%20kit.png',
    specifications: ['Art. No.: 1166', 'Training: Recommended', 'Quantifies: 140+ parameters (see technical data sheet)', 'Made In: Germany', 'Ready to Ship: Usually within 10 days', 'Form: Hard-shell case', 'Dimensions: 432 x 381 x 191 mm', 'Weight: 2.5 kg', 'Shelf-life: n/a', 'Storage temperature: n/a'],
    advantages: ['18-wavelength parallel measurement covering UV, IR and full VIS range', 'Unlock over 140 potential parameters', 'Seamless Connectivity: WiFi, USB, Bluetooth, GSM', 'User-friendly software and mobile app for data management', 'Cloud Sync through free cloud service', 'HD Touch Display for easy navigation'],
  },
  {
    name: 'LETZTEST Visual Arsenic Test Kit',
    slug: 'letztest-visual-arsenic-test-kit',
    category: 'PT',
    description: 'The visual arsenic test kit offers the best value on the market. Based on the latest technology, our test kit delivers accurate results in just a few minutes without requiring any technical expertise.\n\nUnlike other water quality tests, there are no dangerous chemicals required. Straight forward and safe to use, easy to store and easy to transport, it\'s the perfect choice for remote locations.',
    features: ['Detects arsenic', 'Visual results', 'No lab needed', 'Safe testing method'],
    image: '/visual%20arsenic%20kit.png',
    specifications: ['Art. No.: 481303-5 (50 tests), 481304 (100 tests), 481298 (300 tests)', 'Training: No training required', 'Detects: Arsenic; Detection range: <1, 2, 3, 4, 5, 6, 7, 8, 10, 13, 20, 25, 30, 40, >50, >80, >120, >160 ppb (µg/L)', 'Made in: USA', 'Ready to Ship: Upon request, usually 10-14 days', 'Form: Hard-shell case', 'Dimensions: 210 x 260 x 80 mm', 'Weight: 0.9 kg', 'Shelf-life: Upon request', 'Storage temperature: No cooling required'],
    advantages: ['Winner of the 2003 WEF Innovative Technology Award', 'Only 3 reagents and one strip', 'Non-toxic reagents', 'Ideal for field testing requiring no technical training', 'No other equipment needed (no batteries, power or instruments required)', 'Completely non-technical', '14 minutes procedure', 'Can be used with little knowledge of English (reagents clearly marked 1, 2 and 3)'],
  },
  {
    name: 'LETZTEST Mobile Water Lab Box',
    slug: 'letztest-mobile-water-lab-box',
    category: 'CL',
    description: 'The LETZTEST Mobile Water Lab Box is a complete, portable laboratory for on-site water quality testing in off-grid locations. It combines microbiological and physico-chemical analysis tools in one durable, lightweight box. Equipped with electricity-free incubation, photometric testing, sampling gear, and digital data management, it enables professional water monitoring anywhere. Its modular design keeps all instruments organized, protected, and ready for transport — by car, truck, or even motorcycle. This long-term solution also offers direct technical support via QR code and video tutorials.\n\nProven Efficiency Gains – Up to 70% Increase in Lab Efficiency\n\nIndependent evaluations in similar settings (e.g., Government Laboratory at Madi Okollo District Water Department, Uganda, 2024) have shown that the LETZTEST Mobile Water Lab Box can boost operational efficiency by over 70%, enabling more than 100 additional water sources to be tested per quarter with the same budget after switching from emergency relief kits. Users also reported faster data management, lower operational costs, and greater flexibility in the field.',
    features: ['All-in-one design', 'Portable case', 'Multiple test parameters', 'Field-ready'],
    image: '/mobile%20water%20box.png',
    specifications: ['Art. No.: 1190', 'Training: Recommended', 'Purpose: Complete mobile water quality testing laboratory in a box (microbiol. & phys.-chem.)', 'Form: Custom-made hard-shell box', 'Material: Ultra-light, virtually unbreakable special polymer engineered by ThyssenKrupp', 'Dimensions: 58 x 58 x 71 cm (L x W x H)', 'Weight: 55 kg', 'Incl. Testing Parameters in Starter-Set: 27 selected priority parameters: E. coli (Escherichia coli), TC/OC (Total & Other Coliforms), Alk-M (Alkalinity M), Al (Aluminium), NH₃ (Ammonia), As (Arsenic), Cl- (Chloride), Cl₂ (Chlorine – free, combined & total), Col (Colour – Hazen/APHA), Cu (Copper), F- (Fluoride – SPADNS method), TH (LR/HR) (Total Hardness – Low/High Range), Fe (Iron), Pb (Lead) - coming soon, Mn (Manganese), NO₃- (Nitrate), NO₂- (Nitrite), PO₄³- (Phosphate – ortho), SO₄²- (Sulphate), SS (Suspended Solids), Turb (Turbidity), EC (Electric Conductivity), pH (Acidity/Alkalinity), TDS (Total Dissolved Solids), Temp (Temperature)', 'Available opt. Parameters: > 150 parameters (see list of consumables in the Technical Data Sheet)'],
    advantages: ['70% increase in lab efficiency (study-proven, field-proven by independent evaluation)', 'Special recognition by UN-HABITAT and GWOPA', 'Designed for long-term operation (unlike emergency relief field kits)', 'Highest hardware robustness — 100% made in Germany', 'All-in-one solution — test anywhere, anytime, easy and independent'],
  },
  {
    name: 'LETZTEST Portable MiBi Water Lab',
    slug: 'letztest-portable-mibi-water-lab',
    category: 'CL',
    description: 'LETZTEST Portable MiBi Water Lab is a complete, electricity-independent system for on-site microbiological water testing according to DIN EN ISO 9308-1. It enables reliable quantification of E. coli and total coliforms per 100 mL — designed for water quality testing in off-grid locations.\n\nCombining membrane filtration, sampling, and the world\'s only electricity-free incubator in one compact setup, it delivers laboratory-grade results anywhere. The robust, lightweight design keeps all components protected, organized, and easy to transport. Compatible with standard consumables, the system reduces running costs while ensuring accurate, standards-compliant testing. Optional direct technical support is available for end-users.\n\n.',
    features: ['Microbiological testing', 'Portable format', 'On-site results', 'Complete kit'],
    image: '/portable%20mibi%20water%20lab.png',
    specifications: ['Art. No.: 1258', 'Training: Recommended', 'Purpose: For microbiological analysis in water, beverage, and pharmaceutical applications', 'Form: Hard-shell case', 'Material: Robust polymer', 'Dimensions: 450 x 360 x 175 mm (L x W x H)', 'Weight: 8.6 kg', 'Waterproof Rating: IP68', 'Testing Equipment Material: Pharmaceutical-grade stainless steel (1.4404)', 'Filtration Unit: 1-branch manifold, stand-alone', 'Filtration Volume: 100 mL graduated', 'Sterilisation: Flame, autoclave, or other', 'Filter Compatibility: Standard membrane filtration filters for microbiological analysis, Ø 47 mm or 50 mm; pore sizes 0.2 µm or 0.45 µm (cellulose nitrate or other polymers)', 'Sealing Ring: Heat-resistant EPDM clamp seal', 'Detection Limit: 1 CFU / 100 mL (DIN EN ISO 9308-1)', 'Suggested Culture Media: Compact Dry dehydrated culture plates or other ready-to-use chromogenic media. Also compatible with reusable or self-prepared Petri dishes.', 'Incubation: Typically 24 h at 37°C for chromogenic media plates', 'Power Source: Not required', 'Country of Origin: Germany'],
    advantages: ['Ultra-robust: All hardware parts made of thick pharmaceutical-grade stainless steel, produced in Germany', 'Independent of current or battery', 'Low operating costs', 'Quick results', 'Few consumables without requirement of cooling', 'Simplified, methanol-free sterilisation', 'Easy to transport (by motorbike)', 'Simple processes', 'Insensitive to errors', 'Automatic counting of colonies using smartphone app', 'Testing of a larger number of samples compared to comparable kits', 'Robust case with low carbon footprint, made in Italy', 'Rewritable illustrated handbook with easily understandable instructions (English, French, Arabic, Spanish)'],
  },
  {
    name: 'LETZTEST Benchtop MiBi Water Lab',
    slug: 'letztest-benchtop-mibi-water-lab',
    category: 'CL',
    description: 'LETZTEST Benchtop MiBi Lab is a high-capacity microbiological water testing system for laboratories, compliant with DIN EN ISO 9308-1. Designed for stationary use, it quantifies E. coli and other coliform bacteria per 100 mL with laboratory-grade accuracy — while remaining fully portable when projects move off-grid.\n\nThe system combines membrane filtration, a stainless steel water sampler and a large-capacity electricity-free incubator. Unlike conventional incubators, the soft, shock-resistant incubator is not prone to transport damage and operates without mains power, ensuring reliable incubation even during power outages or in off-grid field laboratories. It can incubate up to 100 LETZTEST Tubes or 300 CompactDry Petri Dishes simultaneously.\n\nBuilt for demanding laboratory workflows and temporary project labs alike, the LETZTEST Benchtop MiBi Water Lab reduces transport effort, setup time, and replacement costs while offering exceptional resilience, flexibility in consumables, and low running costs.  for central and remote water laboratories handling large sample volumes.\n\n.',
    features: ['Benchtop design', 'Advanced microbio testing', 'Higher throughput', 'Lab-grade accuracy'],
    image: '/benchtop%20mibi%20water%20lab.png',
    specifications: ['Art. No.: 1259', 'Training: Recommended', 'Quantifies: Escherichia coli and other coliform bacteria in water according to ISO 9308-1:2014 standard. Advantage: The same kit can be used to quantify other relevant bacteria in water such as enterococcus, pseudomonas aeruginosa, heterotrophic bacteria, total count bacteria and many more.', 'Made in: Europe', 'Ready to Ship: Upon request, usually 10 days', 'Form: Hard-shell case', 'Dimensions: 690 x 530 x 285 mm', 'Weight: 24 kg', 'Shelf-life: n/a', 'Storage temperature: Consumables Compact DRY Plates and ChroMedium Coliform Agar - 500g can be stored at room temperature'],
    advantages: ['Independent of current or battery in case of lack of electricity', 'Very low running costs of ~0.50€/sample possible by replacing two consumables with reusable solutions', 'Easy to transport (by motorbike) e.g. to a project laboratory', 'Easy to use', 'Automatic counting of colonies (=result) using a smartphone app', 'Insensitive to errors', 'Few consumables required', 'Easy storage of consumables (no cooling)', 'Simplified, methanol-free sterilisation', 'Testing of a larger number of samples compared to similar kits', 'All parts inside kit made in EU', 'Case with low carbon footprint in high quality and design made in Italy'],
  },
  {
    name: 'LETZTEST Water CheckPack Basic',
    slug: 'letztest-water-checkpack-basic',
    category: 'CL',
    description: 'A fully equipped water testing backpack for rapid water quality assessment in the first 72 hours of an emergency. Independent of electricity and complex procedures, it enables reliable microbiological and physico-chemical testing directly in the field — in parallel for up to three technicians.\n\nDesigned for use by trained laypersons, medical personnel, or health officers as part of an organizational response, it contains all essential tools for sampling, testing, safe waste disposal, clear instructions, data management, and long-lasting consumables.\n\nEasy-to-use LETZTEST Tubes provide rapid microbiological analysis, while LETZTEST Visual Color Comparators and further user-friendly physico-chemical equipment deliver reliable water testing results.',
    features: ['Core parameters', 'Easy to use', 'Budget-friendly', 'Ideal for routine checks'],
    image: '/watee%20checkpack%20basic.png',
    specifications: ['Art. No.: 1221', 'Training: Recommended', 'Purpose: Water quality assessment in the first 72 hours of an emergency', 'Form: High quality emergency response backpack', 'Material: Truck tarpaulin, original CORDURA fabric and 3M Scotchlite reflective strips', 'Dimensions: 470 x 390 x 300 mm (L x W x H)', 'Weight: 9 kg', 'Selected priority parameters: Visual presence/absence: Fecal bacteria incl. E. coli | Visual testing: Al, Cl₂ (free/residual & total), EC, Fe, Mn, NO₃-, pH, TDS, Temp., Turbidity', 'Incubator: Not needed', 'Optional parameters: Additional parameters on request'],
    advantages: ['Team-ready: Designed for simultaneous use by up to three technicians', 'Easy-to-use: Intuitive, user-friendly operation in the field', 'Fully mobile and independent from power supply', 'Long-term & robust: Engineered for demanding environments, built to last', 'Durable backpack with precision foam inserts protects all components', 'Sustainable solution — every component individually replaceable and reorderable', 'All-in-one solution: Complete field solution developed with emergency relief experts'],
  },
  {
    name: 'LETZTEST Water CheckPack Pro',
    slug: 'letztest-water-checkpack-pro',
    category: 'CL',
    description: 'A fully equipped water testing backpack for rapid water quality assessment in the first 72 hours of an emergency. Independent of electricity and complex procedures, it enables reliable microbiological and physico-chemical testing directly in the field — in parallel for up to three technicians.\n\nDesigned for use by trained laypersons, medical personnel, or health officers as part of an organizational response, it contains all essential tools for sampling, testing, safe waste disposal, clear instructions, data management, and long-lasting consumables.\n\nEasy-to-use LETZTEST Tubes provide rapid microbiological analysis, while the state-of-the-art LETZTEST photometer, including cloud-based data management deliver precise physico-chemical water testing results.',
    features: ['Expanded parameters', 'Professional grade', 'Comprehensive kit', 'Field & lab use'],
    image: '/water%20checkpack%20pro.png',
    specifications: ['Art. No.: 1241', 'Training: Recommended', 'Purpose: Water quality assessment in the first 72 hours of an emergency', 'Form: High quality emergency response backpack', 'Material: Truck tarpaulin, original CORDURA fabric and 3M Scotchlite reflective strips', 'Dimensions: 470 x 390 x 300 mm (L x W x H)', 'Weight: 10.2 kg', 'Selected priority parameters: Visual presence/absence: Fecal bacteria incl. E. coli | Photometric: Al, Cl₂ (free/residual & total), EC, F-, Fe, Mn, NO₃-, pH, TDS, Temp., Turbidity', 'Incubator: Not needed', 'Optional parameters: Additional parameters on request'],
    advantages: ['Team-ready: Designed for simultaneous use by up to three technicians', 'Long-term & robust: Engineered for demanding environments, built to last', 'Durable backpack with precision foam inserts, every component replaceable', 'Easy-to-use: Intuitive, user-friendly operation, fully mobile and independent from power supply', 'All-in-one solution: Complete field solution developed with emergency relief experts'],
  },
  {
    name: 'LETZTEST Water CheckPack Pro+',
    slug: 'letztest-water-checkpack-pro-plus',
    category: 'CL',
    description: 'A fully equipped water testing backpack for rapid water quality assessment in the first 72 hours of an emergency. Independent of electricity and complex procedures, it enables reliable microbiological and physico-chemical testing directly in the field — in parallel for up to three technicians.\n\nDesigned for use by trained laypersons, medical personnel, or health officers as part of an organizational response, it contains all essential tools for sampling, testing, safe waste disposal, clear instructions, data management, and long-lasting consumables.\n\nThe LETZTEST Membrane Filtration Set together with an incubator provide reliable microbiological analysis, while the state-of-the-art LETZTEST photometer, including cloud-based data management deliver precise physico-chemical water testing results.',
    features: ['Most comprehensive', 'Premium accessories', 'All parameters included', 'Professional grade'],
    image: '/water%20checkpack%20pro%20plus.png',
    specifications: ['Art. No.: 1275', 'Training: Recommended', 'Purpose: Water quality assessment in the first 72 hours of an emergency', 'Form: High quality emergency response backpack', 'Material: Truck tarpaulin, original CORDURA fabric and 3M Scotchlite reflective strips', 'Dimensions: 470 x 390 x 300 mm (L x W x H)', 'Weight: 11.9 kg', 'Selected priority parameters: Membrane Filtration Method DIN EN ISO 9308-1: E. coli | Photometric: Al, Cl₂ (free/residual & total), EC, F-, Fe, Mn, NO₃-, pH, TDS, Temp., Turbidity', 'Incubator: Needed and included', 'Optional parameters: Additional parameters on request'],
    advantages: ['Team-ready: Designed for simultaneous use by up to three technicians', 'Long-term & robust: Engineered for demanding environments, built to last', 'Durable backpack with precision foam inserts, every component replaceable', 'Easy-to-use: Intuitive, user-friendly operation, fully mobile and independent from power supply', 'All-in-one solution: Complete field solution developed with emergency relief experts'],
  },
  {
    name: 'Water Storage Tank – 1000L',
    slug: 'water-storage-tank-1000l',
    category: 'GP',
    description: 'Durable, food-grade polyethylene water storage tank suitable for household and institutional use.',
    features: ['Food-grade material', 'UV-resistant', 'Easy installation', '10-year warranty'],
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=600&auto=format&fit=crop',
    specifications: ['Capacity: 1000 litres', 'Material: Food-grade polyethylene', 'UV protection: Yes', 'Warranty: 10 years'],
    advantages: ['Food-grade safe material', 'UV-resistant for outdoor use', 'Easy to install', 'Long 10-year warranty'],
  },
  {
    name: 'Activated Carbon Filter Cartridge',
    slug: 'activated-carbon-filter-cartridge',
    category: 'GP',
    description: 'High-quality activated carbon filter for removing chlorine, odors, and organic contaminants from water.',
    features: ['Reduces chlorine & taste', 'High adsorption capacity', 'Standard 10" size', 'Lasts 6 months'],
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=600&auto=format&fit=crop',
    specifications: ['Filtration: Activated carbon', 'Size: Standard 10"', 'Lifespan: 6 months', 'Reduces: Chlorine, odors, organics'],
    advantages: ['Improves taste and odor', 'High adsorption capacity', 'Standard size fits most systems', '6-month lifespan'],
  },
  {
    name: 'Sediment Pre-Filter – 5 Micron',
    slug: 'sediment-pre-filter-5-micron',
    category: 'GP',
    description: 'Spun polypropylene sediment filter for removing sand, rust, and suspended particles from water.',
    features: ['5 micron rating', 'High dirt-holding capacity', 'Universal fit', 'Washable & reusable'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=600&auto=format&fit=crop',
    specifications: ['Micron rating: 5 micron', 'Material: Spun polypropylene', 'Fit: Universal', 'Maintenance: Washable and reusable'],
    advantages: ['Removes sediment and particles', 'High dirt-holding capacity', 'Universal fit for most systems', 'Washable and reusable'],
  },
  {
    name: 'Reverse Osmosis Membrane – 50 GPD',
    slug: 'reverse-osmosis-membrane-50-gpd',
    category: 'GP',
    description: 'High-rejection thin-film composite RO membrane for residential and commercial water purification.',
    features: ['50 gallons per day', '99% rejection rate', 'Thin-film composite', 'Standard 1812 size'],
    image: 'https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?q=80&w=600&auto=format&fit=crop',
    specifications: ['Capacity: 50 GPD', 'Rejection rate: 99%', 'Type: Thin-film composite', 'Size: Standard 1812'],
    advantages: ['High 99% rejection rate', 'Produces 50 gallons daily', 'Standard size for easy replacement', 'Reliable thin-film composite technology'],
  },
  {
    name: 'UV Sterilization Chamber – 12W',
    slug: 'uv-sterilization-chamber-12w',
    category: 'GP',
    description: 'Ultraviolet water sterilizer that eliminates 99.9% of bacteria, viruses, and pathogens without chemicals.',
    features: ['12W UV lamp', '99.9% pathogen kill', 'No chemical residue', 'Low power consumption'],
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=600&auto=format&fit=crop',
    specifications: ['Power: 12W UV lamp', 'Efficiency: 99.9% pathogen kill', 'Method: UV sterilization', 'Power consumption: Low'],
    advantages: ['Chemical-free sterilization', 'Eliminates 99.9% of pathogens', 'Low power consumption', 'No chemical residue in water'],
  },
];
