export type Category = 'All' | 'MT' | 'PT' | 'CL' | 'GP';

export interface Product {
  name: string;
  slug: string;
  category: Category;
  description: string;
  features: string[];
  image: string;
  specifications?: string[];
  advantages?: string[];
}

export const categories: { id: Category; label: string }[] = [
  { id: 'All', label: 'All Products' },
  { id: 'MT', label: 'MT \u2013 Microbiological Testing' },
  { id: 'PT', label: 'PT \u2013 Physico-chemical Testing' },
  { id: 'CL', label: 'ML \u2013 Mobile Laboratory' },
  { id: 'GP', label: 'GP \u2013 General Products' },
];

export const products: Product[] = [
  {
    name: 'LETZTEST Tube',
    slug: 'letztest-tube',
    category: 'MT',
    description: 'Rapid on-site detection of coliform bacteria and E.coli in water sources with easy-to-read results.',
    features: ['Detects coliforms & E.coli', 'Results in 24 hours', 'No lab equipment needed', 'Includes 50 tests'],
    image: '/letztest%20tube.jpeg',
    specifications: ['Test type: Coliform & E.coli detection', 'Result time: 24 hours', 'Test format: Single-use tube', 'Storage: Room temperature'],
    advantages: ['No lab equipment required', 'Easy-to-read color change results', 'Portable and field-ready', 'Cost-effective per test'],
  },
  {
    name: 'LETZTEST Household Water Test Kit',
    slug: 'letztest-household-water-test-kit',
    category: 'MT',
    description: 'Complete kit for testing drinking water quality at home with simple step-by-step instructions.',
    features: ['Tests multiple parameters', 'Easy-to-use format', 'Results in minutes', 'Ideal for home use'],
    image: '/household%20water%20test%20Kit.jpg',
    specifications: ['Parameters tested: Multiple', 'Result time: Minutes', 'Kit contents: Test strips, reagents, guide', 'Shelf life: 12 months'],
    advantages: ['Simple step-by-step instructions', 'No technical training needed', 'Comprehensive home testing', 'Affordable solution'],
  },
  {
    name: 'LETZTEST Portable Membrane Filtration Kit',
    slug: 'letztest-portable-membrane-filtration-kit',
    category: 'MT',
    description: 'Field-ready membrane filtration system for microbiological analysis of water samples on-site.',
    features: ['Portable design', 'Membrane filtration method', 'Field-ready', 'Comprehensive kit'],
    image: '/portable%20membrane.png',
    specifications: ['Filtration method: Membrane filtration', 'Portability: Field-ready', 'Components: Pump, filter holder, membranes', 'Power: Manual or battery'],
    advantages: ['Enables on-site microbiological testing', 'No fixed laboratory required', 'Accurate and reliable results', 'Durable field equipment'],
  },
  {
    name: 'LETZTEST Electricity-Free Incubators',
    slug: 'letztest-electricity-free-incubators',
    category: 'MT',
    description: 'Innovative incubators that maintain 37°C without electricity, ideal for remote field microbiological testing.',
    features: ['No electricity required', 'Maintains 37°C', 'Portable and rugged', 'Multiple sizes available'],
    image: '/electricity%20free.png',
    specifications: ['Temperature: 37°C', 'Power source: None required', 'Sizes: Multiple options', 'Material: Insulated casing'],
    advantages: ['Operates without electricity', 'Ideal for remote field use', 'Consistent temperature maintenance', 'Rugged and durable build'],
  },
  {
    name: 'LETZTEST Benchtop Membrane Filtration Kit',
    slug: 'letztest-benchtop-membrane-filtration-kit',
    category: 'MT',
    description: 'Laboratory-grade membrane filtration system for precise microbiological water quality analysis.',
    features: ['Benchtop design', 'High precision filtration', 'Lab-grade components', 'Reusable setup'],
    image: '/benchtop%20membrane%20filtration.jpg',
    specifications: ['Design: Benchtop', 'Filtration type: Membrane', 'Material: Lab-grade components', 'Setup: Reusable'],
    advantages: ['Laboratory-grade precision', 'Reusable and sustainable', 'Higher throughput capacity', 'Professional quality results'],
  },
  {
    name: 'LETZTEST Water Sampler',
    slug: 'letztest-water-sampler',
    category: 'MT',
    description: 'Sterile water sampling device for collecting uncontaminated water samples for microbiological analysis.',
    features: ['Sterile design', 'Easy to use', 'Prevents cross-contamination', 'Ideal for field sampling'],
    image: '/water%20sampler.png',
    specifications: ['Type: Sterile sampler', 'Use: Water sample collection', 'Features: Cross-contamination prevention', 'Application: Field sampling'],
    advantages: ['Ensures sample integrity', 'Easy to operate', 'Prevents contamination', 'Ideal for field use'],
  },
  {
    name: 'LETZTEST Turbidity Tube',
    slug: 'letztest-turbidity-tube',
    category: 'PT',
    description: 'Simple and accurate turbidity tube for measuring water clarity in field conditions.',
    features: ['Measures turbidity in NTU', 'Easy-to-read scale', 'No batteries required', 'Durable construction'],
    image: '/turbidity%20tube.png',
    specifications: ['Measurement: Turbidity in NTU', 'Power: None required', 'Scale: Easy-to-read', 'Material: Durable'],
    advantages: ['No batteries or power needed', 'Simple visual reading', 'Durable for field conditions', 'Cost-effective turbidity testing'],
  },
  {
    name: 'LETZTEST pH | Chlorine Tester',
    slug: 'letztest-ph-chlorine-tester',
    category: 'PT',
    description: 'Dual-purpose tester for measuring pH levels and chlorine concentration in water samples.',
    features: ['Tests pH and chlorine', 'Fast results', 'Portable design', 'Easy calibration'],
    image: '/chlroine%20tester.png',
    specifications: ['Parameters: pH, Chlorine', 'Result time: Fast', 'Design: Portable', 'Calibration: Easy'],
    advantages: ['Tests two key parameters', 'Quick results', 'Portable and lightweight', 'Simple calibration process'],
  },
  {
    name: 'LETZTEST Visual Color Comparator Kit',
    slug: 'letztest-visual-color-comparator-kit',
    category: 'PT',
    description: 'Complete visual color comparator kit for testing multiple chemical parameters in water.',
    features: ['Color comparison method', 'Tests multiple parameters', 'Includes reagents', '100+ tests per kit'],
    image: '/visual%20color%20comparator.png',
    specifications: ['Method: Visual color comparison', 'Parameters: Multiple chemical', 'Tests per kit: 100+', 'Includes: Reagents and vials'],
    advantages: ['No electronics required', 'Comprehensive parameter coverage', 'High number of tests per kit', 'Field-friendly visual method'],
  },
  {
    name: 'LETZTEST Multimeter Kit',
    slug: 'letztest-multimeter-kit',
    category: 'PT',
    description: 'Multi-parameter water testing kit for comprehensive physico-chemical analysis in the field.',
    features: ['Multiple parameters', 'Digital readout', 'Portable kit', 'Field-ready'],
    image: '/multimeter%20kit.png',
    specifications: ['Type: Multi-parameter', 'Display: Digital readout', 'Portability: Kit format', 'Application: Field & lab'],
    advantages: ['Measures multiple parameters in one device', 'Digital accuracy', 'Portable and convenient', 'All-in-one testing solution'],
  },
  {
    name: 'LETZTEST Photometer Kit',
    slug: 'letztest-photometer-kit',
    category: 'PT',
    description: 'Portable photometer for accurate measurement of chemical parameters in water samples.',
    features: ['Digital photometer', 'High accuracy', 'Multiple test parameters', 'Data logging'],
    image: '/photometer%20kit.png',
    specifications: ['Device: Digital photometer', 'Accuracy: High precision', 'Parameters: Multiple', 'Features: Data logging'],
    advantages: ['Highly accurate measurements', 'Digital data logging', 'Multiple parameter support', 'Professional grade results'],
  },
  {
    name: 'LETZTEST Visual Arsenic Test Kit',
    slug: 'letztest-visual-arsenic-test-kit',
    category: 'PT',
    description: 'Specialized visual test kit for detecting arsenic contamination in drinking water.',
    features: ['Detects arsenic', 'Visual results', 'No lab needed', 'Safe testing method'],
    image: '/visual%20arsenic%20kit.png',
    specifications: ['Target: Arsenic detection', 'Method: Visual', 'Lab requirement: None', 'Safety: Safe testing method'],
    advantages: ['Detects dangerous arsenic levels', 'Visual results easy to interpret', 'Safe testing procedure', 'No laboratory required'],
  },
  {
    name: 'LETZTEST Mobile Water Lab Box',
    slug: 'letztest-mobile-water-lab-box',
    category: 'CL',
    description: 'Compact all-in-one mobile laboratory box for comprehensive water quality testing in the field.',
    features: ['All-in-one design', 'Portable case', 'Multiple test parameters', 'Field-ready'],
    image: '/mobile%20water%20box.png',
    specifications: ['Design: All-in-one mobile lab', 'Format: Portable case', 'Parameters: Multiple', 'Ready for field use'],
    advantages: ['Complete lab in a box', 'Easily transportable', 'Comprehensive testing capability', 'Ready for immediate field use'],
  },
  {
    name: 'LETZTEST Portable MiBi Water Lab',
    slug: 'letztest-portable-mibi-water-lab',
    category: 'CL',
    description: 'Portable microbiological water testing lab for on-site detection of microbial contamination.',
    features: ['Microbiological testing', 'Portable format', 'On-site results', 'Complete kit'],
    image: '/portable%20mibi%20water%20lab.png',
    specifications: ['Testing type: Microbiological', 'Format: Portable', 'Results: On-site', 'Kit: Complete'],
    advantages: ['Enables on-site microbiological testing', 'Portable and field-ready', 'Complete kit with everything needed', 'Rapid results'],
  },
  {
    name: 'LETZTEST Benchtop MiBi Water Lab',
    slug: 'letztest-benchtop-mibi-water-lab',
    category: 'CL',
    description: 'Benchtop microbiological water testing laboratory for more advanced microbial analysis.',
    features: ['Benchtop design', 'Advanced microbio testing', 'Higher throughput', 'Lab-grade accuracy'],
    image: '/benchtop%20mibi%20water%20lab.png',
    specifications: ['Design: Benchtop', 'Testing: Advanced microbiological', 'Throughput: Higher capacity', 'Accuracy: Lab-grade'],
    advantages: ['Advanced testing capability', 'Higher sample throughput', 'Laboratory-grade accuracy', 'Designed for dedicated workspace'],
  },
  {
    name: 'LETZTEST Water CheckPack Basic',
    slug: 'letztest-water-checkpack-basic',
    category: 'CL',
    description: 'Essential water testing kit covering core parameters for routine water quality checks.',
    features: ['Core parameters', 'Easy to use', 'Budget-friendly', 'Ideal for routine checks'],
    image: '/watee%20checkpack%20basic.png',
    specifications: ['Parameters: Core set', 'Ease of use: Simple', 'Price: Budget-friendly', 'Use: Routine checks'],
    advantages: ['Covers essential parameters', 'Very easy to use', 'Budget-friendly option', 'Ideal for regular monitoring'],
  },
  {
    name: 'LETZTEST Water CheckPack Pro',
    slug: 'letztest-water-checkpack-pro',
    category: 'CL',
    description: 'Professional water testing kit with expanded parameter coverage for comprehensive analysis.',
    features: ['Expanded parameters', 'Professional grade', 'Comprehensive kit', 'Field & lab use'],
    image: '/water%20checkpack%20pro.png',
    specifications: ['Parameters: Expanded set', 'Grade: Professional', 'Coverage: Comprehensive', 'Use: Field and lab'],
    advantages: ['More parameters for deeper analysis', 'Professional-grade components', 'Suitable for both field and lab', 'Comprehensive testing solution'],
  },
  {
    name: 'LETZTEST Water CheckPack Pro+',
    slug: 'letztest-water-checkpack-pro-plus',
    category: 'CL',
    description: 'Premium all-in-one water testing solution with the widest range of parameters and accessories.',
    features: ['Most comprehensive', 'Premium accessories', 'All parameters included', 'Professional grade'],
    image: '/water%20checkpack%20pro%20plus.png',
    specifications: ['Parameters: Full range', 'Accessories: Premium', 'Coverage: All parameters', 'Grade: Professional'],
    advantages: ['Complete parameter coverage', 'Premium quality accessories', 'Most comprehensive solution', 'Professional-grade results'],
  },
  {
    name: 'Water Storage Tank – 1000L',
    slug: 'water-storage-tank-1000l',
    category: 'GP',
    description: 'Durable, food-grade polyethylene water storage tank suitable for household and institutional use.',
    features: ['Food-grade material', 'UV-resistant', 'Easy installation', '10-year warranty'],
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=600&auto=format&fit=crop',
    specifications: ['Capacity: 1000 litres', 'Material: Food-grade polyethylene', 'UV protection: Yes', 'Warranty: 10 years'],
    advantages: ['Food-grade safe material', 'UV-resistant for outdoor use', 'Easy to install', 'Long 10-year warranty'],
  },
  {
    name: 'Activated Carbon Filter Cartridge',
    slug: 'activated-carbon-filter-cartridge',
    category: 'GP',
    description: 'High-quality activated carbon filter for removing chlorine, odors, and organic contaminants from water.',
    features: ['Reduces chlorine & taste', 'High adsorption capacity', 'Standard 10" size', 'Lasts 6 months'],
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=600&auto=format&fit=crop',
    specifications: ['Filtration: Activated carbon', 'Size: Standard 10"', 'Lifespan: 6 months', 'Reduces: Chlorine, odors, organics'],
    advantages: ['Improves taste and odor', 'High adsorption capacity', 'Standard size fits most systems', '6-month lifespan'],
  },
  {
    name: 'Sediment Pre-Filter – 5 Micron',
    slug: 'sediment-pre-filter-5-micron',
    category: 'GP',
    description: 'Spun polypropylene sediment filter for removing sand, rust, and suspended particles from water.',
    features: ['5 micron rating', 'High dirt-holding capacity', 'Universal fit', 'Washable & reusable'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=600&auto=format&fit=crop',
    specifications: ['Micron rating: 5 micron', 'Material: Spun polypropylene', 'Fit: Universal', 'Maintenance: Washable and reusable'],
    advantages: ['Removes sediment and particles', 'High dirt-holding capacity', 'Universal fit for most systems', 'Washable and reusable'],
  },
  {
    name: 'Reverse Osmosis Membrane – 50 GPD',
    slug: 'reverse-osmosis-membrane-50-gpd',
    category: 'GP',
    description: 'High-rejection thin-film composite RO membrane for residential and commercial water purification.',
    features: ['50 gallons per day', '99% rejection rate', 'Thin-film composite', 'Standard 1812 size'],
    image: 'https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?q=80&w=600&auto=format&fit=crop',
    specifications: ['Capacity: 50 GPD', 'Rejection rate: 99%', 'Type: Thin-film composite', 'Size: Standard 1812'],
    advantages: ['High 99% rejection rate', 'Produces 50 gallons daily', 'Standard size for easy replacement', 'Reliable thin-film composite technology'],
  },
  {
    name: 'UV Sterilization Chamber – 12W',
    slug: 'uv-sterilization-chamber-12w',
    category: 'GP',
    description: 'Ultraviolet water sterilizer that eliminates 99.9% of bacteria, viruses, and pathogens without chemicals.',
    features: ['12W UV lamp', '99.9% pathogen kill', 'No chemical residue', 'Low power consumption'],
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?q=80&w=600&auto=format&fit=crop',
    specifications: ['Power: 12W UV lamp', 'Efficiency: 99.9% pathogen kill', 'Method: UV sterilization', 'Power consumption: Low'],
    advantages: ['Chemical-free sterilization', 'Eliminates 99.9% of pathogens', 'Low power consumption', 'No chemical residue in water'],
  },
];
